[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps = 
    adafruit/Adafruit LSM6DS
    plerup/EspSoftwareSerial@^8.2.0
    tinyu-zhao/TinyGPSPlus-ESP32@^0.0.2
    adafruit/Adafruit BME280 Library@^2.3.0
    adafruit/Adafruit BMP280 Library@^3.0.0